### ISSUE TITLE
mqtt.sh generation bug

### ISSUE THREAD

**Issue by OptimusGREEN** [BeardedTek-com/fEVR#65]
Hi, 

Getting this issue upon running. It appears that the generated 'run_mqtt_client.sh' file gets the fEVR url without a colon before the port. Had a look to try and fix this in the code but cant see where `fevr = request.form.get('fevr')` comes from in setup.py.

I've manually edited my generated file and added the colon in which makes it run.

Heres the error in docker logs.

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.79.1.1075090', port=80): Max retries exceeded with url: /setup/mqtt/apiAuth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8ada480bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

**Comment by BeardedTek** [comment]
I should be getting back to hacking away this week.  End of school year and yard maintenance time in Alaska right now.

Thank you for the bug reports.

**Comment by OptimusGREEN** [comment]
haha, take yer time dude, I know the feeling of have a todo list the length of your arm.

**Comment by BeardedTek** [comment]
It seems this is caused by my auto detection of the fEVR url in app/templates/setupmqtt.html
```
<script>
                URL = window.location.href.split(":");
                if (URL[0]){
                    https = URL[0]
                }
                fevr = URL[1].split('/')[2]
                if (URL[2]){
                    fevr += URL[2]
                }
                document.querySelector("input[name='https']").value = https;
                document.querySelector("#https").innerHTML = https
                document.querySelector("input[name='fevr']").value = fevr;
                document.querySelector("#fevr").innerHTML = fevr
            </script>
```
I think I will get rid of it all together and just add 3 separate form inputs.

The intent was to allow for both local http requests with port number and https behind a reverse proxy outside the local network.

**Comment by BeardedTek** [comment]
I have a fix in now that ***should*** fix things.

Test away!

**Comment by BeardedTek** [comment]
Not quite...  need to build the fevr url properly...

**Comment by BeardedTek** [comment]
After making a few more changes, it appears I have fixed this issue.  Please feel free to test and report back if you have issues.

**Comment by OptimusGREEN** [comment]
yup, this has fixed this issue 👍 thanks
