### ISSUE TITLE
api url wrong for adding events

### ISSUE THREAD

**Issue by OptimusGREEN** [BeardedTek-com/fEVR#66]
Hi... again :)

it looks like '/setup/mqtt' has been added to the beginning of the api url for adding events. see below 

`[ __main__       ] 1653235607.0042 http://10.79.1.107:5090/setup/mqtt/api/events/add/1653235595.237857-aj7qj2/garden_west/person/78`

**Comment by BeardedTek** [comment]
This is related to #65 and will be addressed in that issue

**Comment by OptimusGREEN** [comment]
This doesn't appear to have been fixed by #65 unfortunately.

`[ __main__       ] 1653513701.6995 <Response [404]>
[ __main__       ] 1653513701.7035 http://10.79.1.107:5090/setup/mqtt/api/events/add/1653513692.922604-7pg469/garden_west/person/67
[ mqtt_client    ] 1653513701.7035 b'<!doctype html>\n<html lang=en>\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n'`

same error.

**Comment by BeardedTek** [comment]
Can you take a screenshot of the setup/mqtt page filled out before clicking submit then again after you click submit?

**Comment by OptimusGREEN** [comment]
![Screen Shot 2022-05-25 at 22 31 42](https://user-images.githubusercontent.com/17599575/170370925-612633f9-cbb2-44e2-8f6d-4800f6cd2699.png)
![Screen Shot 2022-05-25 at 22 32 09](https://user-images.githubusercontent.com/17599575/170370937-71dae76f-acf9-494e-8b51-ef10f707d811.png)

**Comment by OptimusGREEN** [comment]
Its obviously recieving the info from mqtt ok as it detects the event, but cant post to the api as the url has /setup/mqtt/ in it which I'm assuming it shouldn't. if i copy the url and remove that then submit it manually in a browser, the event is recorded. I've had a look at the code and can't see where its coming from.

**Comment by BeardedTek** [comment]
It seems like it's coming from run_mqtt_client.sh

Can you do the following:
- delete run_mqtt_client.sh
- make sure you have the latest code base
```
git commit -- .
git pull
sudo docker pull ghcr.io/beardedtek-com/fevr:main
```
-Make sure you are using the latest docker-compose.yml available in the repository
```
docker-compose up -d
```
- Rerun the mqtt setup process again and see what it does.

**Comment by OptimusGREEN** [comment]
Done.

I couldn't get the web ui to load, done a port scan and 5090 wasn't open so added the ports to the compose file and I'm now getting an internal server error. 

I'll try again tomorrow as 23:15 here now so off to bed. take care.

**Comment by OptimusGREEN** [comment]
I've managed to set up fresh and this issue seems to be resolved. good work

**Comment by BeardedTek** [comment]
Awesome.  Thanks for the help.  Always appreciated.

**Comment by BeardedTek** [comment]
Roger that.  Thanks for the help!

William J Kenny III
The Bearded Tek
***@***.***
https://u22838684.ct.sendgrid.net/ls/click?upn=qENo-2BaQ-2F0-2BrOhG-2Fgfyebc-2FrV3ftULRgXpbvEwnoHuCLWBXdEBV4-2FTpgfVySLE-2FbPNcWv_U31jt5HgHBh7k3Grc5s4lypKAOMq0fuzYgWxiOeQSfOdPgsbrCfagF7JhttTpMzuBn7RkHD83f01i1syfXMebhgnf7i0NH32QMRUaiyP6ThUKt6BVH0NIxup3KOU0OoYHyfi81D3ZNKZ6MVmOcbvjqHQlMmsGTm7ClsuVxkYGHUFsyq8sXkuwJ3I4YA5nCzvNYHpMEN2GZqgvDbvPOMkK4OLVWInsl0-2BsfX-2BJgiVppR8Vny81g5GHhyINgB-2FJumnWgStnzIm3S6VL-2F1a0d5rAg-3D-3D
https://u22838684.ct.sendgrid.net/ls/click?upn=qENo-2BaQ-2F0-2BrOhG-2Fgfyebc-2F7l8k23p8vaRjsOtVXy4d-2F15YS5m9ZMraMapqk-2FvgkC46C__U31jt5HgHBh7k3Grc5s4lypKAOMq0fuzYgWxiOeQSfOdPgsbrCfagF7JhttTpMzuBn7RkHD83f01i1syfXMebhgnf7i0NH32QMRUaiyP6ThUKt6BVH0NIxup3KOU0OoYlhW5ekr9HLUSeS6dENblZXc1Trh6ypK6iZ-2B5p5lItOuoDlopqJ3bdlJH7fW1X6EyigElm7m59cPAeL4VHvMdjWAPncSEHZ8ne0mVTNfgFc-2BkcuvaJqsZ3qUH7kWzEkeSXiclkNRC1KOVe0gm0xMHhg-3D-3D
